// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
	export interface IStyleCss {
		aboutUs: string;
		mainTitle: string;
		textWrapper: string;
	}
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
